/**
 * The songs that use a catalogue progression (US-2.6, AC-2.6.11).
 *
 * A credit names a song, its artist, the section the progression carries, and
 * the catalogue entry it is. Several songs share a loop, and the catalogue keeps
 * one entry per distinct set of chords (AC-2.6.1/15), so a song is credited to
 * the entry rather than given one of its own. Chords only — no lyric is held.
 *
 * Transcribed as scale degrees from each song's own key, so a credit reads true
 * in whatever Key the Pattern is in. Where a song's chord has no quality in the
 * catalogue — a slash chord, an m11, a power chord — the nearest one is used.
 */
/** The artists credited, in the order the Heard in line lists them. */
export const ARTISTS = ['Radiohead', 'The National', 'Wilco', 'Bon Iver', 'Coldplay', 'Bob Dylan'];

/** Each credit: artist, song, section, catalogue entry. Popularity order within an artist. */
export const SONGBOOK = [
  ['Radiohead', 'Creep', 'verse and chorus', 'I-III-IV-iv'],
  ['Radiohead', 'No Surprises', 'verse', 'I-vi7-ii-V-I-iv'],
  ['Radiohead', 'No Surprises', 'chorus', 'ii-V-triads'],
  ['Radiohead', 'Karma Police', 'verse', 'i-IV-v-bVII-i-bVI-v-bVII'],
  ['Radiohead', 'Karma Police', 'chorus', 'bIII-IV-bVII-VI7'],
  ['Radiohead', 'Karma Police', 'outro', 'ii-IV-bVII-IV-bVII-IV-V7'],
  ['Radiohead', 'Let Down', 'verse', 'I-V-vi-V'],
  ['Radiohead', 'Let Down', 'chorus', 'IV-I'],
  ['Radiohead', 'High and Dry', 'verse and chorus', 'ii7-IV-I-I'],
  ['Radiohead', 'Fake Plastic Trees', 'verse', 'I-vi-V-IV'],
  ['Radiohead', 'Fake Plastic Trees', 'chorus', 'ii7-I'],
  ['Radiohead', 'Exit Music', 'verse', 'i-V-bIII-IV-i-V-I'],
  ['Radiohead', 'Weird Fishes/Arpeggi', 'main loop', 'ii7-iii7-V'],
  ['Radiohead', 'Everything in Its Right Place', 'main loop', 'I-bIImaj7-bIII'],
  ['Radiohead', 'Street Spirit', 'riff and verse', 'i-v'],
  ['Radiohead', 'Street Spirit', 'chorus', 'bIII-v-i-i'],
  ['Radiohead', 'Reckoner', 'verse', 'i-bVII-bVI-i-bVI'],
  ['Radiohead', 'Reckoner', 'bridge', 'iii-i-iv-bVImaj7-V'],
  ['Radiohead', 'Lucky', 'verse', 'i-iv-bIII-v-i-bVI-bIII-v'],
  ['Radiohead', 'Lucky', 'chorus', 'IV-i-IV-i-IV-i-bVI-V7'],
  ['Radiohead', 'Just', 'verse', 'vi-bVI-V-#IV-IV'],
  ['Radiohead', 'Just', 'chorus', 'I-bIII-II-IV'],
  ['The National', 'I Need My Girl', 'verse and chorus', 'i-bVI-bIII-bVII'],
  ['The National', 'Light Years', 'intro and verse', 'ii-IV-I-Vsus4'],
  ['The National', 'Bloodbuzz Ohio', 'verse', 'I-vi'],
  ['The National', 'Bloodbuzz Ohio', 'pre-chorus and chorus', 'IV-I'],
  ['The National', 'Fake Empire', 'verse', 'I-IV-V'],
  ['The National', 'Fake Empire', 'chorus', 'vi-IV-V'],
  ['The National', 'Sorrow', 'verse', 'I-iii-vi-V'],
  ['The National', 'About Today', 'main loop', 'IV-vi-vi-V'],
  ['The National', 'Runaway', 'verse', 'I-IVmaj7-I-iii'],
  ['The National', 'Pink Rabbits', 'intro', 'ii-V-I-vi'],
  ['The National', 'Pink Rabbits', 'verse and chorus', 'ii-V-I-IV'],
  ['The National', 'England', 'main loop', 'I-ii-IV-V-IV-ii'],
  ['The National', 'Graceless', 'intro and verse', 'vi-I-IV-I'],
  ['The National', 'Graceless', 'chorus', 'I-IV-I-IV-I-IV-I-V'],
  ['The National', 'Terrible Love', 'verse', 'I-IV'],
  ['The National', 'Terrible Love', 'bridge', 'IV-I-ii-V'],
  ['The National', 'Mr. November', 'verse and chorus', 'vi-IV-I-V'],
  ['The National', 'Guilty Party', 'verse', 'I-iii-vi-IV'],
  ['The National', 'Guilty Party', 'chorus', 'I-V-vi-IV'],
  ['The National', 'Conversation 16', 'verse', 'vi-I-ii-V'],
  ['The National', 'Conversation 16', 'chorus', 'I-IV-vi-IV'],
  ['The National', 'Start a War', 'verse and chorus', 'IV-I-V-vi'],
  ['The National', 'Afraid of Everyone', 'verse and interlude', 'i-bIII-bVI-iv'],
  ['Wilco', 'Jesus, Etc.', 'verse', 'vi-iii-IV-I-ii-V'],
  ['Wilco', 'Jesus, Etc.', 'chorus', 'I-I-vi-III-IV-I-V'],
  ['Wilco', 'California Stars', 'whole song', 'I-V-IV-I'],
  ['Wilco', 'How to Fight Loneliness', 'intro and verse', 'i-bVII6-bVI-V'],
  ['Wilco', 'How to Fight Loneliness', 'chorus', 'iv-bVII-viio7-i'],
  ['Wilco', 'How to Fight Loneliness', 'bridge', 'bIII-bVI'],
  ['Wilco', 'Impossible Germany', 'intro', 'ii7-IVmaj7'],
  ['Wilco', 'Impossible Germany', 'verse', 'ii7-IVmaj7-I-vi7'],
  ['Wilco', 'Heavy Metal Drummer', 'intro and verse', 'I-I-bVII-V'],
  ['Wilco', 'Say You Miss Me', 'intro and verse', 'I-I-vi-V-IV'],
  ['Wilco', 'Say You Miss Me', 'chorus', 'III-vi-IV'],
  ['Wilco', 'Poor Places', 'first part', 'I-V-vi-IV-II7-IV'],
  ['Wilco', 'Poor Places', 'second part', 'I-V-vi-I7'],
  ['Wilco', 'Poor Places', 'second part, later', 'IV-ii7-I-II'],
  ['Wilco', 'Poor Places', 'second part, end', 'IV-iv-I-bVI-IV-I'],
  ['Wilco', 'Kamera', 'verse', 'I-IV-V-IV-I-V'],
  ['Wilco', 'War on War', 'chorus', 'V-ii-V-I'],
  ['Wilco', 'Handshake Drugs', 'intro and verse', 'I-IV-bIII-I'],
  ['Wilco', 'Via Chicago', 'whole song', 'Imaj7-I-V-IV'],
  ['Wilco', 'Hate It Here', 'intro and verse', 'I-IV-iii-IV'],
  ['Wilco', 'Box Full of Letters', 'intro and verse', 'I-V-IV-ii-IV'],
  ['Bon Iver', 'Skinny Love', 'verse', 'vi-I'],
  ['Bon Iver', 'Skinny Love', 'chorus and bridge', 'I-I-IV'],
  ['Bon Iver', 'Holocene', 'verse', 'I-vi-V-IV'],
  ['Bon Iver', 're: Stacks', 'verse', 'Vsus4-I-IVadd9'],
  ['Bon Iver', 're: Stacks', 'chorus', 'Vsus4-vi7-IV'],
  ['Bon Iver', 'Hey, Ma', 'intro', 'vi-I-vi-I-IV-V-IV-V'],
  ['Bon Iver', 'Hey, Ma', 'verse', 'I-IV-vi-V-I-iii-IV-V'],
  ['Bon Iver', 'Hey, Ma', 'chorus', 'vi-IV-vi-IV-vi-V-I'],
  ['Bon Iver', 'Blood Bank', 'intro and verse', 'i7-bVII-bVI'],
  ['Bon Iver', 'Blood Bank', 'second part', 'bIII-bVII-i7-bVI'],
  ['Bon Iver', '8 (circle)', 'main loop', 'IV-I-V-V-vi-IV-I-I'],
  ['Bon Iver', '22 (OVER S∞∞N)', 'main loop', 'I-IV'],
  ['Bon Iver', 'For Emma', 'intro and verse', 'I-iii-IV-I'],
  ['Coldplay', 'Yellow', 'verse', 'I-V6-IVmaj7'],
  ['Coldplay', 'Yellow', 'chorus', 'IV-vi-V'],
  ['Coldplay', 'Something Just Like This', 'verse and chorus', 'bVI-bVII-i-bVII'],
  ['Coldplay', 'Viva La Vida', 'verse', 'IV-V-I-vi'],
  ['Coldplay', 'Viva La Vida', 'chorus', 'IV-V-iii-vi-triads'],
  ['Coldplay', 'The Scientist', 'verse', 'vi7-IV-I-Vsus4'],
  ['Coldplay', 'The Scientist', 'chorus', 'IVadd9-I-V'],
  ['Coldplay', 'Hymn for the Weekend', 'verse', 'iv-bVII-i'],
  ['Coldplay', 'Hymn for the Weekend', 'pre-chorus', 'i-bVI-iv-bVII'],
  ['Coldplay', 'Hymn for the Weekend', 'chorus', 'bVI-bVII-i'],
  ['Coldplay', 'Sparks', 'verse', 'bIIImaj7-i'],
  ['Coldplay', 'Sparks', 'chorus', 'i-imMaj7-i9-i6-bVImaj7'],
  ['Coldplay', 'A Sky Full of Stars', 'verse and chorus', 'vi-IV-I-iii'],
  ['Coldplay', 'Fix You', 'verse', 'I-iii-vi-V'],
  ['Coldplay', 'Fix You', 'chorus', 'IV-I-V-IV'],
  ['Coldplay', 'Fix You', 'bridge', 'I-IV-I-V'],
  ['Coldplay', 'Paradise', 'intro', 'ii-V-vi-I'],
  ['Coldplay', 'Paradise', 'verse', 'vi-IV-I-V'],
  ['Coldplay', 'Paradise', 'chorus', 'ii-IV-I-V'],
  ['Coldplay', 'My Universe', 'verse', 'IV-vi-V'],
  ['Coldplay', 'My Universe', 'chorus', 'IV-vi-V-I'],
  ['Coldplay', 'Adventure of a Lifetime', 'verse and chorus', 'iv-bVII-i'],
  ['Coldplay', 'Clocks', 'riff and verse', 'I-v-v-ii'],
  ['Coldplay', 'Clocks', 'outro', 'I-v-IV'],
  ['Coldplay', 'Every Teardrop Is a Waterfall', 'verse', 'IVsus2-I'],
  ['Coldplay', 'Every Teardrop Is a Waterfall', 'chorus', 'IVsus2-I-vi-V'],
  ['Coldplay', 'Til Kingdom Come', 'chorus', 'vi-IVmaj7-I-V6'],
  ['Coldplay', 'Up&Up', 'verse', 'I-V-vi-IV'],
  ['Coldplay', 'Up&Up', 'chorus', 'I-V-bVII-IV'],
  ['Coldplay', 'Princess of China', 'verse and chorus', 'i-bIII-iv-bVI'],
  ['Bob Dylan', 'Knockin’ on Heaven’s Door', 'verse and chorus', 'I-V-ii-ii-I-V-IV-IV'],
  ['Bob Dylan', 'Like a Rolling Stone', 'verse', 'I-ii-iii-IV-V'],
  ['Bob Dylan', 'Like a Rolling Stone', 'pre-chorus', 'IV-iii-ii-I-ii-IV-V'],
  ['Bob Dylan', 'Like a Rolling Stone', 'chorus', 'I-IV-V-V'],
  ['Bob Dylan', 'The Times They Are A-Changin’', 'verse, opening lines', 'I-vi-IV-I-I-ii-IV-V'],
  ['Bob Dylan', 'The Times They Are A-Changin’', 'verse, closing lines', 'I-ii-V-I-V-IV-V-I-IV-V-I'],
  ['Bob Dylan', 'Blowin’ in the Wind', 'verse', 'I-IV-V-I-I-IV-V'],
  ['Bob Dylan', 'Blowin’ in the Wind', 'chorus', 'IV-V-I-vi-IV-V-I'],
  ['Bob Dylan', 'Make You Feel My Love', 'verse', 'I-V-I7-IV-iv-I-II9-V7sus4'],
  ['Bob Dylan', 'Don’t Think Twice, It’s All Right', 'verse, first half', 'I-V-vi-IV-I-V'],
  ['Bob Dylan', 'Don’t Think Twice, It’s All Right', 'verse, second half', 'I-V-vi-II7-V-V7'],
  ['Bob Dylan', 'Don’t Think Twice, It’s All Right', 'verse turnaround', 'I-I7-IV-II7-I-V-I'],
  ['Bob Dylan', 'Lay, Lady, Lay', 'verse', 'I-iii-bVII-ii'],
  ['Bob Dylan', 'Lay, Lady, Lay', 'refrain', 'V-vi-I'],
  ['Bob Dylan', 'Lay, Lady, Lay', 'bridge', 'iii-V-vi-I'],
  ['Bob Dylan', 'Hurricane', 'verse', 'i-bVI'],
  ['Bob Dylan', 'Hurricane', 'refrain', 'v-i-bVI-bIII-bVII'],
  ['Bob Dylan', 'Mr. Tambourine Man', 'chorus', 'IV-V-I-IV-I-IV-V'],
  ['Bob Dylan', 'Mr. Tambourine Man', 'verse', 'IV-V-I-IV-I-IV-ii-V'],
  ['Bob Dylan', 'Subterranean Homesick Blues', 'verse', 'I7-IV7-I7'],
  ['Bob Dylan', 'Subterranean Homesick Blues', 'refrain', 'V7-I7'],
  ['Bob Dylan', 'All Along the Watchtower', 'verse and interludes', 'i-bVII-bVI-bVII'],
  ['Bob Dylan', 'It Ain’t Me Babe', 'verse', 'I-ii-iii-ii-I'],
  ['Bob Dylan', 'It Ain’t Me Babe', 'chorus', 'IV-V-I'],
  ['Bob Dylan', 'Tangled Up in Blue', 'verse', 'I-bVII'],
  ['Bob Dylan', 'Tangled Up in Blue', 'verse, second half', 'V-vi-I-IV-V'],
  ['Bob Dylan', 'Tangled Up in Blue', 'refrain', 'bVII-I'],
  ['Bob Dylan', 'Just Like a Woman', 'verse', 'I-IV-V-I'],
  ['Bob Dylan', 'Just Like a Woman', 'refrain', 'I-iii-ii-IV'],
  ['Bob Dylan', 'Girl from the North Country', 'verse', 'I-iii-IV-I-IV-I-V-I'],
  ['Bob Dylan', 'One More Cup of Coffee', 'verse', 'andalusian'],
  ['Bob Dylan', 'One More Cup of Coffee', 'chorus', 'bVI-V-i'],
  ['Bob Dylan', 'Shelter from the Storm', 'verse and refrain', 'I-V-IV-I'],
].map(([artist, title, section, progression]) => ({ artist, title, section, progression }));

/**
 * The songs credited to a catalogue entry, grouped by artist in ARTISTS order,
 * each artist's songs in the order they are listed here.
 */
export function heardIn(progressionId) {
  const credits = SONGBOOK.filter((c) => c.progression === progressionId);
  return ARTISTS.map((artist) => ({
    artist,
    songs: credits.filter((c) => c.artist === artist).map(({ title, section }) => ({ title, section })),
  })).filter((group) => group.songs.length > 0);
}

